### ISSUE TITLE
running from repl

### ISSUE THREAD

**Issue by chenbekor** [tillrohrmann/flink-project.g8#1]
when running flink standalone (dev mode) from command line (sbt REPL) - I'm trying to stop the running job and stay in REPL mode...   Ctrl-C and Ctrl-D are ignored.

after adding this to build.sbt :

``` Scala
 cancelable in Global := true
```

hitting ctrl-d is ignored and ctrl-c is indeed honored but will cause flink will not shutdown gracefully. it throws the below stacktrace:

 any clue? 

```
java.lang.InterruptedException: null
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
    at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:439)
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:494)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ExecutorCompletionService$QueueingFuture@34d9df9f rejected from java.util.concurrent.ThreadPoolExecutor@35c8be21[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 158]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
    at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
    at sbt.CompletionService$.submit(CompletionService.scala:28)
    at sbt.ConcurrentRestrictions$$anon$4.submitValid(ConcurrentRestrictions.scala:160)
    at sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:150)
    at sbt.Execute.submit(Execute.scala:226)
```

**Comment by tillrohrmann** [comment]
Hi @chenbekor, I think this is just a side-effect of how sbt cancels the run command. I assume that it does not gracefully shut Flink down and thus you see this exception. But it should not indicate a severe problem other than a termination artifact of sbt.

**Comment by PhilAndrew** [comment]
@chenbekor did you solve this?

**Comment by bvinayakumar** [comment]
I ran into similar exception even though I registered a shutdown hook as shown below. 

  `ShutdownHookUtil.addShutdownHook(() => influxDBSink.close, "Flink Job", log)`

**Exception**

  `[warn] Run canceled.
  [error] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ExecutorCompletionService$QueueingFuture@39685204 rejected from java.util.concurrent.ThreadPoolExecutor@72d0196d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 202]
  [error]         at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
  [error]         at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
  [error]         at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
  [error]         at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
  [error]         at sbt.CompletionService$.submit(CompletionService.scala:36)
  [error]         at sbt.ConcurrentRestrictions$$anon$4.submitValid(ConcurrentRestrictions.scala:176)
  [error]         at sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:165)
  [error]         at sbt.Execute.submit(Execute.scala:262)
  [error]         at sbt.Execute.ready(Execute.scala:242)
  [error]         at sbt.Execute.notifyDone(Execute.scala:181)
  [error]         at sbt.Execute.$anonfun$retire$2(Execute.scala:152)
  [error]         at sbt.Execute.$anonfun$retire$2$adapted(Execute.scala:151)
  [error]         at scala.collection.immutable.List.foreach(List.scala:389)
  [error]         at sbt.Execute.retire(Execute.scala:151)
  [error]         at sbt.Execute.$anonfun$work$2(Execute.scala:279)
  [error]         at sbt.Execute$$anon$1.process(Execute.scala:24)
  [error]         at sbt.Execute.next$1(Execute.scala:104)
  [error]         at sbt.Execute.processAll(Execute.scala:107)
  [error]         at sbt.Execute.runKeep(Execute.scala:84)
  [error]         at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:387)
  [error]         at sbt.EvaluateTask$.run$1(EvaluateTask.scala:386)
  [error]         at sbt.EvaluateTask$.runTask(EvaluateTask.scala:405)
  [error]         at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:100)
  [error]         at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:331)
  [error]         at sbt.internal.Aggregation$.timedRun(Aggregation.scala:98)
  [error]         at sbt.internal.Aggregation$.runTasks(Aggregation.scala:111)
  [error]         at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:174)
  [error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
  [error]         at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:387)
  [error]         at sbt.MainLoop$.processCommand(MainLoop.scala:153)
  [error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
  [error]         at sbt.State$$anon$1.runCmd$1(State.scala:242)
  [error]         at sbt.State$$anon$1.process(State.scala:248)
  [error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
  [error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
  [error]         at sbt.MainLoop$.next(MainLoop.scala:136)
  [error]         at sbt.MainLoop$.run(MainLoop.scala:129)
  [error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
  [error]         at sbt.io.Using.apply(Using.scala:22)
  [error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
  [error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
  [error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
  [error]         at sbt.MainLoop$.runLogged(MainLoop.scala:34)
  [error]         at sbt.StandardMain$.runManaged(Main.scala:113)
  [error]         at sbt.xMain.run(Main.scala:76)
  [error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
  [error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
  [error]         at xsbt.boot.Launch$.run(Launch.scala:109)
  [error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
  [error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
  [error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
  [error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
  [error]         at xsbt.boot.Boot$.main(Boot.scala:18)
  [error]         at xsbt.boot.Boot.main(Boot.scala)
  [error] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ExecutorCompletionService$QueueingFuture@39685204 rejected from java.util.concurrent.ThreadPoolExecutor@72d0196d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 202]
  [error] Use 'last' for the full log.`

Is there any method to gracefully shutdown Flink execution which I can include into the shutdown hook?
